### ISSUE TITLE
Ecountered crash that is fixed when mod is removed

### ISSUE THREAD

**Issue by smiglssss** [tttsaurus/Fluid-Interaction-Tweaker#2] opened 2024-09-03 20:40 UTC
https://pastecode.io/s/p1yce4ej

**Comment by tttsaurus** [comment] 2024-09-04 01:56
it seems it crashes because of fluidlogged api.

what did you do in game? i don't reproduce this crash by simply adding fluidlogged

**Comment by tttsaurus** [comment] 2024-09-04 03:36
close it for now

**Closed by tttsaurus** 2024-09-04 03:36 UTC
